name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: developeriq-cluster
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: auth-service
  IMAGE: gcr.io/${{ secrets.GKE_PROJECT }}/niruddya98/auth-service
  TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Docker Image
        run: docker build -t $IMAGE:$TAG .

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Configure Docker
        run: gcloud --quiet auth configure-docker

      - name: Push Docker Image to GCR
        run: docker push $IMAGE:$TAG

      - name: Set up kubectl
        uses: GoogleCloudPlatform/github-actions/setup-gke@master
        with:
          cluster-name: $GKE_CLUSTER
          location: $GKE_ZONE
          project-id: $PROJECT_ID
          service-account-key: ${{ secrets.GKE_SA_KEY }}

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/${DEPLOYMENT_NAME} ${DEPLOYMENT_NAME}=${IMAGE}:${TAG}
          kubectl rollout status deployment/${DEPLOYMENT_NAME}
